---
title: "PMV_BD8_stations_kmeans"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Clustering of BIXI stations with kmeans

```{r}
library(tidyverse,quietly = TRUE,warn.conflicts = FALSE)
library(cluster)
library(factoextra)
library(ggplot2)
library(fpc)
library(NbClust)
```
```{r}
#"Script R"" is the current working directory
#preparing the data: adding capacity and nunber of trajets of 2017 to each station.
stations_1 = read.csv(file = "../Data/Stations_2017-5.csv",header = TRUE,sep = ",")
stations_2 = read.csv(file = "../Data/stations_capacity.csv",head = TRUE,sep = ",")
bixistations = merge(stations_1,stations_2,by = intersect(names(stations_1),names(stations_2)))

deplacement2017 = read.csv(file = "../Data/deplacement/nombreDeplacement2017.csv",sep = '\t')
bixistations = merge(bixistations,deplacement2017,by=intersect(names(bixistations),names(deplacement2017)))
bixistations = mutate(bixistations, postal_short = substring(postal,1,3))
head(bixistations)
str(bixistations)
```

```{r}
stations_groupby_postal = group_by(bixistations,postal_short)    
stations_by_group = summarise(stations_groupby_postal,n=n())
stations_by_group = stations_by_group[order(stations_by_group$n,decreasing = TRUE),]
stations_by_group
```

```{r}
kBixi <- bixistations[,c("latitude","longitude","altitude","capacity","numOfTrajets")]
head(kBixi)
kBixi = scale(kBixi)
head(kBixi)
```

```{r}
# determine the best nunber of cluster
nb <- NbClust(kBixi, distance = 'euclidean', min.nc = 2, max.nc = 10, method = 'complete', index = 'all')
```

```{r}
# when number of clusters is 2
km.res <- eclust(kBixi, 'kmeans',k = 2, graph = TRUE)
#how many stations in each cluster
km.res$size
```

```{r}
# when the number of cluster is 10
km.res <- eclust(kBixi, 'kmeans',k = 10, graph = TRUE)
#how many stations in each cluster
km.res$size
```

```{r}
# when the number of cluster is 5
km.res <- eclust(kBixi, 'kmeans',k = 5, graph = TRUE)
#how many stations in each cluster
km.res$size
```

```{r}

```
